; only use this when creating mods, remove this section on release
[debug_mode]
enabled = true

; handles how the game controls
; each of the speed values are multipliers
[movement]
full_360 = true
walk_speed = 1.2
swim_speed = 1.3
dash_speed = 1.5
pop_speed = 1.15

; enables the randomizer's nice items, everything below is toggled together
; nice bombs - place as many bombs as you want at once
; nice hookshot - hookshot any surface
; nice magic rod - no limit on how much you can shoot
[nice_items]
bombs = true
hookshot = false
rod = true
sword = false

; removes the blur around the edge of the screen
; credit to theboy181 for this patch
[blur_removal]
enabled = true

; forces the game to always target 60fps
; credit to HerculeHercule1 for this patch
[stable_fps]
enabled = true

; modes - None, Normal, OHKO
[damage]
mode = normal

; enables the randomizer specific patches
[randomizer]
enabled = false
free_book = false
stealing = standard
enemies = false
enemy_sizes = false