; only use this when creating mods, remove this section on release
[debug_mode]
enabled = true

; handles how the game controls
; Standard = uses control stick, snaps to 8 directions
; Extra = uses control stick, has full 360 degree control
; Dpad = control stick is rendered useless, full control given to dpad
[control_scheme]
movement = extra

; enables the randomizer's nice items, everything below is toggled together
; nice bombs - place as many bombs as you want at once
; nice hookshot - hookshot any surface
; nice magic rod - no limit on how much you can shoot
[nice_items]
bombs = true
hookshot = true
rod = true
sword = true

; removes the blur around the edge of the screen
[blur_removal]
enabled = true

; increases player speed (x1.15 PoP speed multiplier) for walking and swimming
[speed_hack]
enabled = true

; enables the randomizer specific patches
[randomizer_compatible]
enabled = true